version: '3'
services:
    app:
        build: .
        image: ghcr.io/alexandr-horton/courses-top:develop
        container_name: courses-top
        restart: always
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=production
