name: Publish Docker

on:
    push:
        branches: [main]

permissions:
    packages: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@v4
              with:
                  registry: ghcr.io
                  name: ghcr.io/alexander-horton/courses-top
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  tags: 'develop'
